name: assets_gen
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
